services:
  - docker

before_install:
  - docker-compose up -d db

install:
  - docker-compose build

script:
  - docker-compose run --rm web python manage.py test

deploy:
  skip_cleanup: true
  provider: script
  script: deploy/on_travis.sh
  on:
    branch: master
