services:
  - docker

before_install:
  - docker-compose up -d db

install:
  - docker-compose build
  - docker-compose run --rm web python manage.py migrate

before_script:
  - sleep 10

script:
  - docker-compose run --rm web python manage.py test
