sudo: false

cache: pip

language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r website/base-requirements.txt

script:
  - python website/manage.py test --settings=core.settings.test

deploy:
  skip_cleanup: true
  provider: script
  script: deploy/on_travis.sh
  on:
    branch: master
