sudo: false
language: python
services:
  - "docker"

install:
  - make build

script:
  - make test

deploy:
  skip_cleanup: true
  provider: script
  script: deploy/on_travis.sh
  on:
    branch: master
