services:
  - docker

before_install:

install:
  - docker-compose build
  - docker-compose run --rm web python wait-postgre.sh
  - docker-compose run --rm web python manage.py migrate

script:
  - docker-compose run --rm web python manage.py test
