services:
  - docker

env:
  - CONFIG_FILE=docker-compose.test.yml

install:
  - make build

script:
  - make test

deploy:
  skip_cleanup: true
  provider: script
  script: deploy/on_travis.sh
  on:
    branch: master
