sudo: false
language: python
python:
  - "3.6"

install:
  - pip install -r website/requirement.txt

script:
  - python manage.py test --settings=core.settings.test

deploy:
  skip_cleanup: true
  provider: script
  script: deploy/on_travis.sh
  on:
    branch: master
