version: '2'

services:

  web:
    build: ./website
    ports:
      - 8000:8000

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
