version: '2'

services:
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    volumes:
      - ./website:/app
    env_file:
      - config.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
    depends_on:
      - db
      - mail

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  db:
    extends:
      file: docker-compose.common.yml
      service: db

volumes:
  db-data:
    driver: local
