version: '2'

services:
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    env_file:
      - config.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    depends_on:
      - db
    command: ./entrypoints/prod.sh
    restart: always

  db:
    extends:
      file: docker-compose.common.yml
      service: db
    restart: always

  collectstatic:
    extends:
      file: docker-compose.common.yml
      service: web
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    volumes:
      - ./public:/app/public
    command: python3 manage.py collectstatic --noinput

  wiki:
    extends:
      file: docker-compose.common.yml
      service: wiki

  syncwiki:
    extends:
      file: docker-compose.common.yml
      service: syncwiki


volumes:
  db-data:
    driver: local
