version: '2'

services:

    web:
        build: ./website
        ports:
            - 8000:8000
        volumes:
            - ./website:/app
        depends_on:
            - db

    db:
        image: mariadb
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_DATABASE=ava
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3307:3306

volumes:
    db-data:
        driver: local
