version: '2'

services:

    web:
        build: ./website
        ports:
            - 8000:8000
        volumes:
            - ./website:/app
        environment:
            - DJANGO_SETTINGS_MODULE=core.settings.dev
        depends_on:
            - db
            - mail

    mail:
        image: schickling/mailcatcher
        ports:
            - 1080:1080

    db:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data/

volumes:
    db-data:
        driver: local
