version: '2'

services:

  web:
    build: ./website
    volumes:
      - ./uploads:/data
    ports:
      - 8000:8000

  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/

  wiki:
    build:
      context: ./wiki_docker
      dockerfile: Dockerfile.wiki
    ports:
      - 4567:80
    volumes:
      - ./wiki:/wiki
    command: gollum --port 80 --base-path /wiki --no-edit --live-preview --user-icons gravatar

  syncwiki:
    build:
      context: ./wiki_docker
      dockerfile: Dockerfile.syncwiki
    volumes:
      - ./wiki:/wiki
      - ./ssh:/root/.ssh


volumes:
  db-data:
    driver: local
