version: '2'

services:

  web:
    build: ./website
    volumes:
      - ./uploads:/data
      - ./wiki:/wiki
    ports:
      - 8000:8000

  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  db-data:
    driver: local
