# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
