# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160916_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_await_validation',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
