# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 09:09
from __future__ import unicode_literals

import core.behaviors
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_profile_email_await_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('token', models.CharField(default=user.models.generate_token, max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.behaviors.Expirationable, models.Model),
        ),
        migrations.AlterField(
            model_name='emailvalidationtoken',
            name='token',
            field=models.CharField(default=user.models.generate_token, max_length=50, unique=True),
        ),
    ]
