# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:14
from __future__ import unicode_literals

from django.db import migrations


fixture_username = [
    'official',
    'register',
    'login',
    'logout',
    'reset-password',
    'reset-link',
    'profile',
]

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ForbiddenUsername = apps.get_model("user", "ForbiddenUsername")
    db_alias = schema_editor.connection.alias
    username_to_create = [ForbiddenUsername(username=u) for u in fixture_username]
    ForbiddenUsername.objects.using(db_alias).bulk_create(username_to_create)

def reverse_func(apps, schema_editor):
    ForbiddenUsername = apps.get_model("user", "ForbiddenUsername")
    db_alias = schema_editor.connection.alias
    for u in fixture_username:
        ForbiddenUsername.objects.using(db_alias).filter().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170625_1714'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
