# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
