# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utils
import plugins.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins', '0002_auto_20170427_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=main.utils.generate_token, max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Plugin')),
            ],
        ),
        migrations.AlterField(
            model_name='release',
            name='archive',
            field=models.FileField(upload_to=plugins.models.plugin_directory_path),
        ),
        migrations.AddField(
            model_name='downloadrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Release'),
        ),
    ]
