# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_auto_20170508_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrelease',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
