# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_auto_20170609_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='nb_download',
            field=models.IntegerField(default=0),
        ),
    ]
