# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_auto_20170609_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='nb_upvote',
            field=models.IntegerField(default=0),
        ),
    ]
