# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 21:02
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('plugins', '0010_plugin_nb_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
