# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0011_release_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='description',
        ),
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
