# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0012_auto_20170623_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Plugin')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Release')),
            ],
        ),
    ]
