# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0013_plugincommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='readme',
            field=models.TextField(default=''),
        ),
    ]
