# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0015_release_readme_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ['nb_upvote', 'nb_download']},
        ),
    ]
