# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0016_auto_20170625_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['version']},
        ),
        migrations.AddField(
            model_name='release',
            name='checksum',
            field=models.CharField(default='', max_length=64),
        ),
    ]
