# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0017_auto_20170704_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-version']},
        ),
    ]
