# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0018_auto_20170704_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplugins',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plugins.Release'),
        ),
    ]
