# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fixture_os'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstallerFiles',
            new_name='CoreInstaller',
        ),
    ]
