# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170625_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreinstaller',
            name='instruction',
            field=models.TextField(default=''),
        ),
    ]
